sudo: false
language: rust

cache:
  cargo: true
  directories:
    - $HOME/gcc-arm-none-eabi-6_2-2016q4
    - $HOME/uncrustify-uncrustify-0.65
  pip: true

os:
  - linux

addons:
  apt:
    packages:
      - libboost-dev

rust:
  - nightly-2017-06-20

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis-install-gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH="$PATH:$HOME/gcc-arm-none-eabi-6_2-2016q4/bin"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH="$PATH:$HOME/uncrustify-uncrustify-0.65/build"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user mbed-cli; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user colorama pyserial prettytable jinja2 intelhex junit_xml pyyaml requests mbed_ls mbed_host_tests mbed_greentea beautifulsoup4 fuzzywuzzy; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:mosquitto-dev/mosquitto-ppa -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install mosquitto; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then brew tap ARMmbed/homebrew-formulae; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then brew install arm-none-eabi-gcc uncrustify; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then pip install --user mbed-cli; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH$TRAVIS_EVENT_TYPE" == "masterpush" ]]; then pip install --user colorama pyserial prettytable jinja2 intelhex junit_xml pyyaml requests mbed_ls mbed_host_tests mbed_greentea beautifulsoup4 fuzzywuzzy; fi

before_script:
  - (cargo install --vers 0.7.1 rustfmt || true)
  - (cargo install xargo || true)
  - npm install -g markdown-toc
  - npm install --prefix ./server/uplink/lora-receiver
  - npm install --prefix ./server/uplink/http-receiver
  - npm install --prefix ./server/uplink/metadata-tagger
  - npm install --prefix ./server/lab11/packet-parser
  - npm install --prefix ./server/test/test-server

script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then ./run_tests.sh; fi
