#define DEBUG_LED PB_0
#define MOD_OUT PB_3
#define MOD_IN PB_5
#define PPS PA_0
#define SERIAL_TX PA_2
#define SERIAL_RX PA_3
#define I2C_MASTER_SDA PB_4
#define I2C_MASTER_SCL PA_7
#define I2C_SLAVE_SDA PA_10
#define I2C_SLAVE_SCL PA_9
